#include<stdio.h>
#include<malloc.h>
#include<string.h>

enum node_type {PRIMARY_EXPRESSION, POSTFIX_EXPRESSION, ARGUMENT_EXPRESSION_LIST, UNARY_EXPRESSION, UNARY_OPERATOR, CAST_EXPRESSION, MULTIPLICATIVE_EXPRESSION, ADDITIVE_EXPRESSION, SHIFT_EXPRESSION, RELATIONAL_EXPRESSION, EQUALITY_EXPRESSION, AND_EXPRESSION, EXCLUSIVE_OR_EXPRESSION, INCLUSIVE_OR_EXPRESSION, LOGICAL_AND_EXPRESSION, LOGICAL_OR_EXPRESSION, CONDITIONAL_EXPRESSION, ASSIGNMENT_EXPRESSION, ASSIGNMENT_OPERATOR, EXPRESSION, DECLARATION, DECLARATION_SPECIFIERS, INIT_DECLARATOR_LIST, INIT_DECLARATOR, TYPE_SPECIFIER, SPECIFIER_QUALIFIER_LIST, DECLARATOR, DIRECT_DECLARATOR, PARAMETER_TYPE_LIST, PARAMETER_LIST, PARAMETER_DECLARATION, IDENTIFIER_LIST, ABSTRACT_DECLARATOR, INITIALIZER, INITIALIZER_LIST, DESIGNATION, DESIGNATOR_LIST, DESIGNATOR, STATEMENT, LABELED_STATEMENT, COMPOUND_STATEMENT, BLOCK_ITEM_LIST, BLOCK_ITEM, EXPRESSION_STATEMENT, SELECTION_STATEMENT, ITERATION_STATEMENT, JUMP_STATEMENT, TRANSLATION_UNIT, EXTERNAL_DECLARATION, FUNCTION_DEFINITION, DECLARATION_LIST};

typedef struct 
{
	int enum_type; 
	
	char* type;	 
	char* name;	

	struct a_node* left;
	struct a_node* right;
	struct a_node* a;
	struct a_node* b;
	struct a_node* c;
} a_node;

